version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
  auth-service:
    build: ./auth-service
    ports:
      - "3002:3002"
  cart-service:
    build: ./cart-service
    ports:
      - "3003:3003"
